
// <auto-generated />
namespace DesigntimeSourcecodeGenerator.Demo.Model
{
	using System;
	using System.Windows;
	using System.Windows.Controls;
	using System.ComponentModel;

	/// <summary>
	/// このクラスはMainWindowModelクラスの定義によって、自動生成されました。
	/// このファイルをエディタで直接編集しないでください。
	/// </summary>
	public partial class MainWindowModel
	{
#region Logger
		/// <summary>
		/// Logger
		/// </summary>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1311:StaticReadonlyFieldsMustBeginWithUpperCaseLetter", Justification = "Reviewed.")]
		private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
#endregion
#region Singleton
		/// <summary>
		/// Singleton
		/// </summary>
		public static readonly MainWindowModel Instance = new MainWindowModel();

		static MainWindowModel()
		{
			StaticConstructor();
		}
		private MainWindowModel()
		{
			this.InstanceConstructor();
		}
		//static void StaticConstructor() {}
		//private void InstanceConstructor() {}
#endregion
	}
}
